"""
Integration tests for Part 3, mapped directly to architecture.md 3.3's
Definition of Done:

    "correct metadata or a clear validation error for real and
     deliberately-broken files; tiles a large image without ever loading
     the full array (verify with a memory-profiled test); correctly
     reports offset on a misaligned pair."

Needs the full stack (rasterio, pydantic) and the fixtures generated by
test-data/generate_fixtures.py. Not executable in the build sandbox that
produced this code — see PART3_BUILD_NOTES.md. The fast, dependency-light
tests in test_core_logic.py exercise the same underlying algorithms and
WERE run there.

Setup:
    pip install -r requirements.txt
    python test-data/generate_fixtures.py
    pytest tests/test_integration.py -v
"""

import os
try:
    import resource
except ImportError:
    resource = None
import sys

import pytest
import numpy as np
import rasterio
from rasterio.transform import from_origin
from rasterio.crs import CRS

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from backend.shared.schemas import Modality, TaskType, Evidence, Detection, Confidence
from backend.preprocessing import validate_and_prepare, tile_image, check_coregistration, stitch_detections
from backend.preprocessing import config

FIXTURE_DIR = os.path.join(os.path.dirname(__file__), "..", "test-data")


def _fixture(name: str) -> str:
    path = os.path.join(FIXTURE_DIR, name)
    if not os.path.exists(path):
        pytest.skip(
            f"fixture {name} not found — run `python test-data/generate_fixtures.py` first"
        )
    return path


@pytest.fixture(autouse=True)
def _isolated_data_dir(tmp_path, monkeypatch):
    """Each test gets its own throwaway content-hash store, so tests never
    collide with each other or with a previous run's data/ directory."""
    monkeypatch.setattr(config, "DATA_DIR", str(tmp_path / "data"))


# ============================================================================
# validate_and_prepare — "correct metadata or a clear validation error for
# real and deliberately-broken files"
# ============================================================================

def test_valid_optical_file_produces_correct_metadata():
    meta = validate_and_prepare(_fixture("optical_scene.tif"), Modality.OPTICAL, "2026-01-15")
    assert meta.is_valid is True
    assert meta.validation_errors == []
    assert meta.width == 1024 and meta.height == 1024
    assert meta.band_count == 4
    assert meta.modality == Modality.OPTICAL
    assert meta.crs is not None
    assert meta.cog_path and os.path.exists(meta.cog_path)
    assert meta.timestamp == "2026-01-15"


def test_valid_sar_file_produces_correct_metadata():
    meta = validate_and_prepare(_fixture("sar_scene.tif"), Modality.SAR, None)
    assert meta.is_valid is True
    assert meta.band_count == 1
    assert meta.modality == Modality.SAR
    assert meta.cog_path and os.path.exists(meta.cog_path)


def test_truncated_file_fails_cleanly_without_hanging():
    meta = validate_and_prepare(_fixture("malformed_truncated.tif"), Modality.OPTICAL, None)
    assert meta.is_valid is False
    assert len(meta.validation_errors) >= 1
    assert meta.cog_path == ""


def test_non_tiff_file_fails_cleanly():
    meta = validate_and_prepare(_fixture("malformed_not_a_tiff.tif"), Modality.OPTICAL, None)
    assert meta.is_valid is False
    assert len(meta.validation_errors) >= 1


def test_huge_declared_dims_rejected_by_pixel_cap_before_any_read():
    # ~4.1 billion declared pixels in a near-empty sparse file. If this were
    # somehow fully decoded it would be tens of GB / minutes of work -- the
    # guard must reject it fast, from metadata alone.
    import time

    t0 = time.time()
    meta = validate_and_prepare(_fixture("malformed_huge_dims.tif"), Modality.OPTICAL, None)
    elapsed = time.time() - t0

    assert meta.is_valid is False
    assert any("pixel count exceeds cap" in e for e in meta.validation_errors)
    assert meta.width == 64000 and meta.height == 64000  # the metadata probe DID read the true dims
    assert meta.cog_path == ""  # never got to COG conversion
    assert elapsed < 10, f"pixel-cap rejection took {elapsed:.1f}s — should be near-instant, metadata-only"


def test_missing_file_fails_cleanly():
    meta = validate_and_prepare("/nonexistent/path/does_not_exist.tif", Modality.OPTICAL, None)
    assert meta.is_valid is False
    assert meta.width == 0 and meta.cog_path == ""


def test_wrong_extension_fails_cleanly():
    meta = validate_and_prepare(_fixture("optical_scene.tif").replace(".tif", ".jpg"), Modality.OPTICAL, None)
    # this path doesn't exist (we didn't create a .jpg copy) -- still must fail cleanly, not raise
    assert meta.is_valid is False


# ============================================================================
# tile_image — "tiles a large image without ever loading the full array
# (verify with a memory-profiled test)"
# ============================================================================

def _write_large_test_image_windowed(path: str, size: int, bands: int, block: int = 512) -> None:
    """Writes a size x size x bands uint16 GeoTIFF block-by-block via
    windowed writes, so even *generating* this fixture never holds the full
    array in memory — consistent with the same windowed-I/O discipline
    tile_image() itself is being tested for."""
    from rasterio.windows import Window

    profile = {
        "driver": "GTiff", "height": size, "width": size, "count": bands,
        "dtype": "uint16", "crs": CRS.from_epsg(32643),
        "transform": from_origin(500000.0, 2000000.0, 10.0, 10.0),
        "compress": "DEFLATE", "tiled": True, "blockxsize": block, "blockysize": block,
    }
    rng = np.random.default_rng(11)
    with rasterio.open(path, "w", **profile) as dst:
        for row_off in range(0, size, block):
            h = min(block, size - row_off)
            for col_off in range(0, size, block):
                w = min(block, size - col_off)
                chunk = rng.integers(0, 8000, size=(bands, h, w), dtype=np.uint16)
                dst.write(chunk, window=Window(col_off, row_off, w, h))


def test_tile_image_never_loads_full_array_into_memory(tmp_path):
    if resource is None:
        pytest.skip("Memory RSS check requires the Unix-only resource module.")
    size, bands = 8192, 4
    large_path = str(tmp_path / "large_optical.tif")
    _write_large_test_image_windowed(large_path, size=size, bands=bands)

    meta = validate_and_prepare(large_path, Modality.OPTICAL, None)
    assert meta.is_valid, meta.validation_errors

    mem_before_kb = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    tiles = tile_image(meta.image_id, TaskType.GROUNDING, tile_size=1024, overlap_pct=0.1)
    mem_after_kb = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss

    full_array_kb = size * size * bands * 2 / 1024  # uint16 = 2 bytes/px
    additional_kb = mem_after_kb - mem_before_kb

    assert len(tiles) > 1
    assert additional_kb < full_array_kb * 0.5, (
        f"tiling used {additional_kb:.0f} KB additional peak RSS, suspiciously close to "
        f"the full array size ({full_array_kb:.0f} KB) — suggests a full-array read occurred"
    )


def test_tile_image_produces_schema_valid_tiles_covering_the_image():
    meta = validate_and_prepare(_fixture("optical_scene.tif"), Modality.OPTICAL, None)
    tiles = tile_image(meta.image_id, TaskType.GROUNDING, tile_size=256, overlap_pct=0.1)
    assert len(tiles) > 1
    for t in tiles:
        assert t.image_id == meta.image_id
        assert os.path.exists(t.array_path)
        assert len(t.affine_transform) == 6
        with rasterio.open(t.array_path) as ds:
            assert ds.width == t.width and ds.height == t.height
            arr = ds.read()
            assert arr.dtype == np.float32
            assert 0.0 <= arr.min() and arr.max() <= 1.0  # normalized


def test_tile_image_identical_grid_for_same_dimension_images():
    meta_before = validate_and_prepare(_fixture("bitemporal_before.tif"), Modality.OPTICAL, None)
    meta_after = validate_and_prepare(_fixture("bitemporal_after_small.tif"), Modality.OPTICAL, None)
    tiles_before = tile_image(meta_before.image_id, TaskType.CHANGE_DETECTION, tile_size=256, overlap_pct=0.15)
    tiles_after = tile_image(meta_after.image_id, TaskType.CHANGE_DETECTION, tile_size=256, overlap_pct=0.15)
    offsets_before = [(t.col_off, t.row_off) for t in tiles_before]
    offsets_after = [(t.col_off, t.row_off) for t in tiles_after]
    assert offsets_before == offsets_after


# ============================================================================
# check_coregistration — "correctly reports offset on a misaligned pair"
# ============================================================================

def test_check_coregistration_small_shift_is_aligned_and_auto_corrected():
    meta_a = validate_and_prepare(_fixture("bitemporal_before.tif"), Modality.OPTICAL, None)
    meta_b = validate_and_prepare(_fixture("bitemporal_after_small.tif"), Modality.OPTICAL, None)
    result = check_coregistration(meta_a.image_id, meta_b.image_id)

    # fixture's true shift magnitude ~ hypot(2.5, 3.0) = 3.9px
    assert result.aligned is True
    assert result.auto_corrected is True
    assert 1.0 < result.offset_px < 10.0
    assert result.reason is not None


def test_check_coregistration_large_shift_is_not_aligned():
    meta_a = validate_and_prepare(_fixture("bitemporal_before.tif"), Modality.OPTICAL, None)
    meta_b = validate_and_prepare(_fixture("bitemporal_after_large.tif"), Modality.OPTICAL, None)
    result = check_coregistration(meta_a.image_id, meta_b.image_id)

    # fixture's true shift magnitude = hypot(18, 24) = 30px
    assert result.aligned is False
    assert result.offset_px > config.COREG_MAX_ALIGNMENT_THRESHOLD_PX
    assert "refuse" in result.reason.lower() or "exceed" in result.reason.lower()


def test_check_coregistration_identical_image_against_itself_is_aligned():
    meta = validate_and_prepare(_fixture("optical_scene.tif"), Modality.OPTICAL, None)
    result = check_coregistration(meta.image_id, meta.image_id)
    assert result.aligned is True
    assert result.offset_px < config.COREG_NEGLIGIBLE_OFFSET_PX + 0.5


# ============================================================================
# stitch_detections
# ============================================================================

def _make_tile_evidence(task, model, detections, warnings=None):
    return Evidence(
        task=task, model_used=model, modality_used=[Modality.OPTICAL],
        detections=detections, confidence=Confidence(value=0.8, band="HIGH", basis="test fixture"),
        warnings=warnings or [],
    )


def test_stitch_detections_deduplicates_overlapping_tile_boundary_detections():
    meta = validate_and_prepare(_fixture("optical_scene.tif"), Modality.OPTICAL, None)
    # simulates the same real-world building detected independently by two
    # overlapping tiles, already in full-image coordinates (as Part 4 would return)
    tile_ev_1 = _make_tile_evidence(
        TaskType.GROUNDING, "grounding-dino-mock",
        [Detection(label="building", box_px=[100, 100, 150, 150], mask_rle=None, score=0.92)],
    )
    tile_ev_2 = _make_tile_evidence(
        TaskType.GROUNDING, "grounding-dino-mock",
        [Detection(label="building", box_px=[102, 101, 152, 151], mask_rle=None, score=0.85)],
    )
    tile_ev_3 = _make_tile_evidence(
        TaskType.GROUNDING, "grounding-dino-mock",
        [Detection(label="building", box_px=[900, 900, 950, 950], mask_rle=None, score=0.7)],  # far away, distinct
    )
    merged = stitch_detections([tile_ev_1, tile_ev_2, tile_ev_3], meta.image_id)

    assert merged.task == TaskType.GROUNDING
    assert len(merged.detections) == 2  # the near-duplicate pair collapsed to 1, plus the distinct one
    scores = sorted(d.score for d in merged.detections)
    assert scores == [0.7, 0.92]  # kept the higher-scoring one of the duplicate pair


def test_stitch_detections_rejects_mixed_task_types():
    meta = validate_and_prepare(_fixture("optical_scene.tif"), Modality.OPTICAL, None)
    ev_a = _make_tile_evidence(TaskType.GROUNDING, "m", [])
    ev_b = _make_tile_evidence(TaskType.CAPTIONING, "m", [])
    with pytest.raises(ValueError):
        stitch_detections([ev_a, ev_b], meta.image_id)
