"""
CROMA optical + SAR fusion specialist.

Reads SatQuery GeoTIFF tiles and converts them into the channel layout
expected by TorchGeo's pretrained CROMA model.

CROMA expects:
    Optical: [B, 12, 120, 120]
    SAR:     [B, 2, 120, 120]

This specialist currently exposes the pretrained joint representation.
It does NOT pretend that CROMA itself produces natural-language answers
or object detections.
"""

from __future__ import annotations

from collections import OrderedDict
from pathlib import Path
from typing import Any

import numpy as np
import rasterio
import torch
import torch.nn.functional as F
from torchgeo.models import CROMA, CROMABase_Weights


class CROMAFusionModel:
    """Pretrained CROMA optical-SAR fusion model."""

    def __init__(self, device: str = "cpu") -> None:
        self.device = torch.device(device)

        self.model = CROMA().eval()

        # TorchGeo stores CROMA's pretrained checkpoint as five
        # nested state dictionaries. Flatten them to match the
        # CROMA module hierarchy.
        raw_state = CROMABase_Weights.CROMA_VIT.get_state_dict()

        state_dict = OrderedDict(
            (
                f"{module_name}.{key}",
                value,
            )
            for module_name, module_state in raw_state.items()
            for key, value in module_state.items()
        )

        # attn_bias is generated by CROMA from its architecture and
        # therefore is not stored in the checkpoint.
        self.model.load_state_dict(state_dict, strict=False)

        self.model.to(self.device)

    @staticmethod
    def _read_geotiff(path: str) -> np.ndarray:
        """Read a GeoTIFF as [bands, height, width]."""

        path_obj = Path(path)

        if not path_obj.exists():
            raise FileNotFoundError(f"GeoTIFF not found: {path}")

        with rasterio.open(path_obj) as src:
            array = src.read()

        if array.ndim != 3:
            raise ValueError(
                f"Expected GeoTIFF with [bands,H,W], got {array.shape}"
            )

        return array.astype(np.float32)

    @staticmethod
    def _to_120_tensor(array: np.ndarray, expected_bands: int) -> torch.Tensor:
        """
        Convert a GeoTIFF array into [1,C,120,120].

        CROMA was pretrained on 120x120 inputs.
        """

        if array.shape[0] != expected_bands:
            raise ValueError(
                f"Expected {expected_bands} bands, got {array.shape[0]}"
            )

        tensor = torch.from_numpy(array).unsqueeze(0)

        # Replace invalid numeric values before normalization.
        tensor = torch.nan_to_num(
            tensor,
            nan=0.0,
            posinf=0.0,
            neginf=0.0,
        )

        # Per-band min/max normalization.
        # This keeps arbitrary GeoTIFF value ranges bounded before
        # sending them through the pretrained encoder.
        flat = tensor.flatten(start_dim=2)

        min_value = flat.amin(dim=2, keepdim=True).unsqueeze(-1)
        max_value = flat.amax(dim=2, keepdim=True).unsqueeze(-1)

        tensor = (tensor - min_value) / (
            max_value - min_value + 1e-6
        )

        tensor = F.interpolate(
            tensor,
            size=(120, 120),
            mode="bilinear",
            align_corners=False,
        )

        return tensor

    def _load_optical(self, path: str) -> torch.Tensor:
        array = self._read_geotiff(path)

        # CROMA optical branch expects Sentinel-2 style 12-band input.
        return self._to_120_tensor(
            array,
            expected_bands=12,
        )

    def _load_sar(self, path: str) -> torch.Tensor:
        array = self._read_geotiff(path)

        # CROMA SAR branch expects 2 channels.
        return self._to_120_tensor(
            array,
            expected_bands=2,
        )

    @torch.inference_mode()
    def fuse(
        self,
        optical_path: str,
        sar_path: str,
        prompt: str | None = None,
    ) -> dict[str, Any]:
        """
        Run CROMA on one optical + SAR GeoTIFF pair.

        Args:
            optical_path: Path to optical GeoTIFF with 12 bands.
            sar_path: Path to SAR GeoTIFF with 2 bands.
            prompt: Accepted for compatibility with FusionAdapter.
                    CROMA itself does not consume text.

        Returns:
            Joint and modality-specific representations.
        """

        optical = self._load_optical(optical_path)
        sar = self._load_sar(sar_path)

        optical = optical.to(self.device)
        sar = sar.to(self.device)

        outputs = self.model(
            x_sar=sar,
            x_optical=optical,
        )

        return {
            "sar_GAP": outputs["sar_GAP"],
            "optical_GAP": outputs["optical_GAP"],
            "joint_GAP": outputs["joint_GAP"],
            "joint_encodings": outputs["joint_encodings"],
            "text": None,
            "detections": [],
        }